# Generated by Django 3.2.6 on 2021-12-09 20:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='default.jpg', upload_to='profile_images')),
                ('bio', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default=' Street basketball Afternoon-night outdoorTrip to Join City Court ', editable=False, max_length=127)),
                ('meet_day', models.DateField(default=datetime.date.today, unique=True)),
                ('content', models.TextField(default=' Welcome to join pickup basketball trips to the street basketball court. This is a City Pickup Basketball meeting board for 1 day. This is a simple app and a small tool developed to plan and organize basketball trips to the court. A feature is to give sport athletes, players and friend groups insight into who is coming to play ball and when on which weekdays. Can be used to give updates on the current number of how many players who are there (reported arrival), and got plans to ball a given day (pickup basketball time: early afternoon kl. 16 to night ca. kl. 21). You can cancel your attendance on a trip at any time, so anyone can see your presence updated.  If a meeting day is not found in feeds list, just create one! A requirement is to add a new day when you plan to come, so more players can join a trip ', editable=False)),
                ('created_on', models.DateTimeField(default=datetime.date.today)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('dislikes', models.ManyToManyField(blank=True, related_name='dislikes', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
