# Generated by Django 3.2.6 on 2021-12-31 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_remove_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_on',
        ),
        migrations.AddField(
            model_name='post',
            name='created_by_user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.SlugField(blank=True, editable=False, help_text='If blank, the slug will be generated automatically from given ..', max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default=' Join pickup basketball trips to street basketball courts in Oslo, Norway', editable=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(default='Basketball Trip Meetday', help_text='Basketball Trip Meetday', max_length=500),
        ),
    ]
