# Generated by Django 3.2.6 on 2022-01-02 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211231_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='meet_day',
            field=models.DateField(default=datetime.date.today, error_messages={'unique': 'There cannot be 2 trips meetings on the same date. A player has already created a trip for others to sign up on this day. Check out feed list page for all BBall meetings on weekdays.'}, unique=True),
        ),
    ]
