# Generated by Django 3.2.6 on 2022-01-28 13:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20220123_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='like',
            name='value',
            field=models.CharField(choices=[('Im Coming & Playing this day (Sign Up)', 'Im Coming & Playing this day (Sign Up)'), ('You are already Signed up to join. Change your presence -> (Sign out)', 'You are already Signed up to join. Change your presence -> (Sign out)')], default='Im Coming & Playing this day (Sign Up)', max_length=80),
        ),
    ]
