# Generated by Django 3.2.6 on 2022-01-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20220128_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_id',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
